# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Futurobot
description:      'Я разрабатываю мобильные приложения, интересуюсь вебом. Это мой блог.'
url:              http://futurobot.ru
baseurl:          /

author:
  name:           'futurobot'
  url:            https://twitter.com/the_futurobot

paginate:         5

github:           https://github.com/futurobot/
twitter:          https://twitter.com/the_futurobot

gems:
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM